# Generated by Django 5.2.3 on 2025-06-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(unique=True)),
                ('album_id', models.CharField(max_length=50, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('conductor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('songs', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(unique=True)),
                ('conductor_id', models.CharField(max_length=50, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('albums', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
