# Generated by Django 5.2.3 on 2025-06-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classical_music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('song_id', models.CharField(max_length=50, unique=True)),
                ('album_id', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('composer', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('movements', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
