# Generated by Django 5.2.3 on 2025-07-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classical_music", "0002_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="conductor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="album_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="conductor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="album",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
