# Generated by Django 5.2.3 on 2025-07-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classical_music", "0003_album_conductor_name_song_album_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
